const WATCHES = [
  {
    id: "nomos-club-campus",
    brand: "NOMOS Glashütte",
    model: "Club Campus 38",
    price: "Sapphire back • White dial • Leather strap",
    why: "Clean, minimalist German design — Bauhaus spirit with personality and depth.",
    specs: ["38mm case", "Manual winding", "Sapphire exhibition back"],
    vibe: ["Minimal", "German", "Daily wearable"],
    link: "https://teddybaldassarre.com/products/club-campus-38-sapphire-back-white-on-leather-strap",
    image: "https://cdn.shopify.com/s/files/1/0516/0259/0356/products/Nomos_Club_Campus_38_White_Leather_1.jpg",
  },
  {
    id: "shinola-canfield-c56",
    brand: "Shinola",
    model: "Canfield C56 Chronograph",
    price: "Cream dial • Chronograph",
    why: "Bold but refined chrono that’s fashion-forward without loud logos.",
    specs: ["Chronograph", "Cream dial", "Sporty-dress blend"],
    vibe: ["Modern", "Sporty", "Minimalist edge"],
    link: "https://www.shinola.com/products/canfield-c56-chronograph-watch-cream",
    image: "https://cdn.shinola.com/media/catalog/product/cache/8f7b5e9a1b7a7c6a7e3a5d0a1d4b1c8a/c/a/canfield-c56-chronograph-cream_1.jpg",
  },
  {
    id: "nomos-metro-33",
    brand: "NOMOS Glashütte",
    model: "Metro 33 Sage",
    price: "Sage dial • Elegant minimalist",
    why: "Distinctively modern take on a minimalist design; unique color adds character.",
    specs: ["33mm case", "Automatic", "Sage green dial"],
    vibe: ["Minimal", "Modern", "Elegant"],
    link: "https://nomos-glashuette.com/en-us/metro/metro-33-sage-1124.sb",
    image: "https://nomos-glashuette.com/media/catalog/product/cache/4/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/n/o/nomos_metro_33_sage_1124.jpg",
  },
  {
    id: "sternglas-hamburg-argo",
    brand: "Sternglas",
    model: "Hamburg Automatik Edition Argo",
    price: "Black dial • Bauhaus inspired",
    why: "Clean minimalist design with subtle Bauhaus influences and everyday wearability.",
    specs: ["40mm case", "Automatic", "Black dial"],
    vibe: ["Minimal", "German", "Classic"],
    link: "https://www.sternglas.com/products/hamburg-automatik-edition-argo",
    image: "https://cdn.shopify.com/s/files/1/1633/9390/products/sternglas-hamburg-argo-black_1800x1800.png",
  },
  {
    id: "sternglas-naos-darkgreen",
    brand: "Sternglas",
    model: "Naos Automatik Dark Green Bronze",
    price: "Dark green dial • Bronze accents",
    why: "Modern minimalist with a twist — color and material combo that feels unique and stylish.",
    specs: ["40mm case", "Automatic", "Green dial"],
    vibe: ["Minimal", "Modern", "Unique"],
    link: "https://www.sternglas.com/products/naos-automatik-darkgreen-bronze",
    image: "https://cdn.shopify.com/s/files/1/1633/9390/products/sternglas-naos-darkgreen-bronze_1800x1800.png",
  },
];
